-- you can execute this only on the primary replica
-- this script configures node for read-routing, setup the routing URL and also configure the routing list

-- 
ALTER AVAILABILITY GROUP [ag1]  
 MODIFY REPLICA ON  
N'ag-node000' WITH   
(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY));  
GO
ALTER AVAILABILITY GROUP [ag1]  
 MODIFY REPLICA ON  
N'ag-node000' WITH   
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://ag-node000:1433'));  
GO
  
ALTER AVAILABILITY GROUP [ag1]  
 MODIFY REPLICA ON  
N'ag-node001' WITH   
(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY));  
GO
ALTER AVAILABILITY GROUP [ag1]  
 MODIFY REPLICA ON  
N'ag-node001' WITH   
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://ag-node001:1433'));  
GO

ALTER AVAILABILITY GROUP [ag1]  
 MODIFY REPLICA ON  
N'ag-node002' WITH   
(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY));  
GO
ALTER AVAILABILITY GROUP [ag1]  
 MODIFY REPLICA ON  
N'ag-node002' WITH   
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://ag-node002:1433'));  
GO

ALTER AVAILABILITY GROUP [ag1]   
MODIFY REPLICA ON  
N'ag-node000' WITH   
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=(('ag-node001','ag-node002'),'ag-node000')));  
GO

ALTER AVAILABILITY GROUP [ag1]   
MODIFY REPLICA ON  
N'ag-node001' WITH   
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=(('ag-node000','ag-node002'),'ag-node001')));  
GO

ALTER AVAILABILITY GROUP [ag1]   
MODIFY REPLICA ON  
N'ag-node002' WITH   
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=(('ag-node001','ag-node000'),'ag-node002')));  
GO
